# Generated by Django 5.1 on 2025-09-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, null=True, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('numero', models.PositiveIntegerField(max_length=10, verbose_name='Número')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.cliente')),
            ],
        ),
    ]
