# Generated by Django 5.1 on 2025-09-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_cliente_vendas_itensvenda_perfilclientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvenda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='aplicacao.vendas'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='aplicacao.cliente'),
        ),
        migrations.AlterField(
            model_name='perfilclientes',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
    ]
