# Generated by Django 4.2.14 on 2025-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_itensvenda_venda_vendas_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evaluation', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_helpfulness', models.CharField(blank=True, max_length=20, null=True)),
                ('review_score', models.FloatField()),
                ('review_time', models.IntegerField()),
                ('review_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
